spring:
  cloud:
    stream:
      bindings:
        # This will be the output channel name on which producer and consumer need to agree
        # This will, by default, become a pub/sub type queue
        # The channel will create a rabbitmq exchange or kafka topic (or whatever the binder supports)
        consumer:
          destination: greetings
        directConsumer:
          destination: directGreetings

server:
  port: 8000
