spring:
  cloud:
    stream:
      bindings:
        consumer:
          destination: greetings
        directConsumer:
          destination: directGreetings
          group: direct-group
#          durableSubscription: true
server:
  port: 0