spring:
  cloud:
    stream:
      bindings:
        consumer:
          destination: greetings
        directConsumer:
          destination: directGreetings
          group: direct-group
#      rabbit:
#        bindings:
#          directConsumer:
#            consumer:
#              durableSubscription: false
server:
  port: 0
endpoints:
  sensitive: false
